# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--rjF03U3_RSu5qAYIGV58cIpUdIEST8
"""

import pandas as pd
teacher=pd.DataFrame({'FISH': ['Xalilov. D. A', 'Jalilov .M', 'Araboyev . A', 'Aloydinov.M', 'Qadamova. Z','Jorayeva. G','Xontorayev. S', 'Abdullayeva. M', 'Turdimatov.M' ],
    'Utish darsi': ['Suniy intlekt asoslari','Kom. tashkil etish','Kibrxavsizlik asoslari', 'Kom. tash. etish', 'Suniy intlekt asoslari', 'Eliktronika sixemalar', 'Malumotlar tuz va algo', 'Malumotlar tuz va algo', 'Kibrxavsizlik asoslari'],
     'Fan yunalish turi': ['Maruza', 'Maruza', 'Amaliy','Amaliy','Amaliy','Amaliy Maruza','Maruza', 'Amaliy', 'Maruza' ]
})
print (teacher);